ALTER TABLE "Map" ADD COLUMN IF NOT EXISTS "helpAskBatchId" TEXT;
ALTER TABLE "Map" ADD COLUMN IF NOT EXISTS "helpAskAt" TIMESTAMP(3);
ALTER TABLE "Map" ADD COLUMN IF NOT EXISTS "helpAskById" TEXT;

DO $$ BEGIN
  ALTER TABLE "Map" ADD CONSTRAINT "Map_helpAskById_fkey"
    FOREIGN KEY ("helpAskById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "Map_helpAskBatchId_idx" ON "Map"("helpAskBatchId");
