import type { OpsActivityMessage } from "../types/activity";

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

/** Shown when the API returns no milestone events — manager demo preview */
export const DEMO_OPS_UPDATES: OpsActivityMessage[] = [
  {
    id: "demo-update-1",
    action: "upload_approved",
    note: "Dashboard upload approved — ready for field mapping",
    createdAt: hoursAgo(5),
    team: "graphics",
    user: { id: "demo-qa", name: "Maya Rosen" },
    map: {
      id: "demo-map-0103",
      mapNumber: "MAP-2024-0103",
      client: "Urban Retail",
      mapperName: null,
      opsManagerComment: null,
      assignedInspector: { name: "David Levi" },
      assignedQa: { name: "Maya Rosen" },
      assignedSupervisor: null,
    },
  },
  {
    id: "demo-update-2",
    action: "inspector_done",
    note: "Prep complete — sent to upload review",
    createdAt: hoursAgo(6),
    team: "graphics",
    user: { id: "demo-inspector", name: "David Levi" },
    map: {
      id: "demo-map-0102",
      mapNumber: "MAP-2024-0102",
      client: "CityShop",
      mapperName: null,
      opsManagerComment: null,
      assignedInspector: { name: "David Levi" },
      assignedQa: null,
      assignedSupervisor: null,
    },
  },
  {
    id: "demo-update-3",
    action: "fix_done",
    note: "Aisle label fixes completed per QA notes",
    createdAt: hoursAgo(4),
    team: "graphics",
    user: { id: "demo-inspector", name: "David Levi" },
    map: {
      id: "demo-map-0107",
      mapNumber: "MAP-2024-0107",
      client: "GreenGrocer",
      mapperName: null,
      opsManagerComment: null,
      assignedInspector: { name: "David Levi" },
      assignedQa: { name: "Maya Rosen" },
      assignedSupervisor: null,
    },
  },
  {
    id: "demo-update-4",
    action: "qa_approved",
    note: "Polish approved — ready for activation",
    createdAt: hoursAgo(3),
    team: "graphics",
    user: { id: "demo-qa", name: "Maya Rosen" },
    map: {
      id: "demo-map-99",
      mapNumber: "MAP-99",
      client: "MegaStore",
      mapperName: null,
      opsManagerComment: null,
      assignedInspector: { name: "David Levi" },
      assignedQa: { name: "Maya Rosen" },
      assignedSupervisor: null,
    },
  },
  {
    id: "demo-update-5",
    action: "hub_completed",
    note: "MAP-2024-0114 field mapping complete — marked by Alex Ben-Ami",
    createdAt: hoursAgo(1.5),
    team: "ops",
    user: { id: "demo-sup", name: "Alex Ben-Ami" },
    map: {
      id: "demo-map-0114",
      mapNumber: "MAP-2024-0114",
      client: "Grand Market",
      mapperName: "Field Team A",
      opsManagerComment: null,
      assignedInspector: { name: "David Levi" },
      assignedQa: null,
      assignedSupervisor: { name: "Alex Ben-Ami" },
    },
  },
  {
    id: "demo-update-6",
    action: "hub_uncompleted",
    note: "Alex Ben-Ami marked MAP-2024-0115 uncompleted — Could not finish aisle 4 — need return visit tomorrow",
    createdAt: hoursAgo(0.75),
    team: "ops",
    user: { id: "demo-sup", name: "Alex Ben-Ami" },
    map: {
      id: "demo-map-0115",
      mapNumber: "MAP-2024-0115",
      client: "MiniStop",
      mapperName: "Contractor C",
      opsManagerComment: "Could not finish aisle 4 — need return visit tomorrow",
      assignedInspector: { name: "David Levi" },
      assignedQa: null,
      assignedSupervisor: { name: "Alex Ben-Ami" },
    },
  },
  {
    id: "demo-update-7",
    action: "field_complete",
    note: "Released to graphics for polish after field work",
    createdAt: hoursAgo(8),
    team: "ops",
    user: { id: "demo-ops", name: "Rachel Ops" },
    map: {
      id: "demo-map-0105",
      mapNumber: "MAP-2024-0105",
      client: "Corner Store",
      mapperName: "Field Team B",
      opsManagerComment: null,
      assignedInspector: { name: "David Levi" },
      assignedQa: null,
      assignedSupervisor: { name: "Alex Ben-Ami" },
    },
  },
  {
    id: "demo-update-8",
    action: "hub_uncompleted",
    note: "Dana Weiss marked MAP-2024-0113 uncompleted — Mapper left early, sections 2–3 remaining",
    createdAt: hoursAgo(2),
    team: "ops",
    user: { id: "demo-sup2", name: "Dana Weiss" },
    map: {
      id: "demo-map-0113",
      mapNumber: "MAP-2024-0113",
      client: "Daily Mart",
      mapperName: "Field Team B",
      opsManagerComment: "Mapper left early, sections 2–3 remaining",
      assignedInspector: { name: "David Levi" },
      assignedQa: null,
      assignedSupervisor: { name: "Dana Weiss" },
    },
  },
];
